[package]
name = "hyper-router"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
hyper = "~0.11"
futures = "~0.1"
tokio-core = "~0.1"
regex = "~0.2"

[features]
unstable = []
